### ISSUE TITLE
Crashing when trying play a local file

### ISSUE THREAD

**Issue by mizzunet** [alexmercerind/harmonoid#62]
**To Reproduce**
Steps to reproduce the behaviour:
1. Open the app
2. Try to play any music files
3. See it's crashing

**Expected behaviour**
Play the song

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: OnePlus 5
 - OS: Android 11
 - Browser Brave
 - Version 0.0.5

## Logs
https://del.dog/akyppudape

**Comment by alexmercerind** [comment]
Hi there @mizzunet !

Thanks a lot for the report.
May you please try out the latest APK built by GitHub actions here from the 'Artifacts': [Run 2426117306](https://github.com/alexmercerind/harmonoid/runs/2426117306).

And, you can trust this APK because it is not compiled by me, but automated runs on GitHub with debug signatures.

Please let me know, if this fixes your issue.
